### PR TITLE
Added counties, statutes, and primary sponsors field to Bill class in…

### PR DESCRIPTION
**Pull request by jtd00123**
… items.py file

### CODE REVIEW

**Comment by curleypg** [comment]
This is good @jtd00123 , are you interested in doing more work on this project at CodeForCharlotte meet up nights?

**Comment by jtd00123** [comment]
Thanks!  I couldn't make it today, but I can work on it in the future.

**Comment by jtd00123** [comment]
Added 2017 primary sponsors extraction in the nc_leg_bills_spider.py file.

**Comment by curleypg** [comment]
Awesome and thank you @jtd00123 

I did notice that sometimes it doesn't get all the primary sponsors on a bill. It looks like this happens maybe when one of the sponsors has a First Initial Last Name? I'm not sure. I can tell you it only got one primary sponsor, "R. Turner", from this [bill](https://www.ncleg.net/gascripts/BillLookUp/BillLookUp.pl?Session=2017&BillID=H16) but there are 4 listed.

**Comment by jtd00123** [comment]
No worries.  I originally thought that (primary) identified the one name prior, as opposed to the entire row.  I can look at it later soon.

**Pull request merged**
