### PR TITLE
fixed bug where only one primary sponsor appeared in json file

### PR DESCRIPTION
**Pull request by jtd00123**
Added new line that allowed collection of previous siblings relating to target node.  The fix is for 2017 sessions only.

### CODE REVIEW

**Comment by jtd00123** [comment]
The fix is for 2017 sessions only.

**Comment by curleypg** [comment]
My testing on your code is not outputting primary_sponsors for session=2017. I'll be at C4C tomorrow (19 Feb) if you want to put our heads together on this.

**Comment by curleypg** [comment]
Wow, forget everything I just wrote as I was checking the wrong branch...Looks good! Hope to see you sometime at Community meet up night.

**Comment by jtd00123** [comment]
I'll be there as well.

**Comment by jtd00123** [comment]
I'm here.

**Comment by jtd00123** [comment]
Wasn't sure if you wanted to separate chapters and sections in "statutes".  Wasn't in my notes but we may have discussed it.  I will fix it if needed.

**Comment by curleypg** [comment]
The sections list appears to follow a `Chapter-Statute` so we can know which chapters are being referenced. That being said I think we're OK with your list and we could parse this data in the app knowing these patters, if needed. Thanks!

**Pull request merged**
